image: php:7.2

pipelines:
  default:
    - step:
        name: security
        caches:
          - composer
          - vendor
        script:
          - apt-get update && mkdir -p /usr/share/man/man1 && mkdir -p /usr/share/man/man7 && apt-get install -yqq git unzip libfreetype6-dev libjpeg62-turbo-dev zlib1g-dev libpq-dev
          - docker-php-ext-install zip
          - docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
          - docker-php-ext-install -j$(nproc) gd
          - curl -sS https://getcomposer.org/installer | php
          - mv composer.phar /usr/local/bin/composer
          - composer install --no-interaction
          - php artisan security-check:now
    - parallel:
      - step:
          name: code convention
          caches:
            - vendor
          script:
            - vendor/bin/php-cs-fixer fix --verbose --dry-run --allow-risky=yes
      - step:
          name: code standard
          caches:
            - vendor
          script:
            - vendor/bin/phpmd app text cleancode,controversial,codesize,naming,design
      - step:
          name: code analyse
          caches:
            - composer
            - vendor
          script:
            - php artisan code:analyse
    - step:
        name: unit testing & code coverage
        caches:
          - composer
          - vendor
        script:
          - apt-get update -yqq && mkdir -p /usr/share/man/man1 && mkdir -p /usr/share/man/man7 && apt-get install -yqq git postgresql-client-9.6 unzip libfreetype6-dev libjpeg62-turbo-dev zlib1g-dev libpq-dev
          - docker-php-ext-install pdo_pgsql && docker-php-ext-install zip && docker-php-ext-install bcmath
          - docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
          - docker-php-ext-install -j$(nproc) gd
          - pecl install xdebug
          - docker-php-ext-enable xdebug
          - curl -sS https://getcomposer.org/installer | php
          - mv composer.phar /usr/local/bin/composer
          - composer install --no-interaction
          - php -r "copy('.env.bitbucket-pipelines', '.env');"
          - php artisan migrate --seed
          - vendor/bin/phpunit
          - php code-coverage.php clover.xml 80
        services:
          - postgres

definitions:
  caches:
    composer: ~/.composer/cache
    vendor: vendor/
  services:
    postgres:
      image: postgres:9.6
      environment:
        POSTGRES_DB: 'homestead'
        POSTGRES_USER: 'root'
        POSTGRES_PASSWORD: 'secret'