version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:8080"
        volumes:
            - .:/application/pajak
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network
    php:
        build: ./docker/php
        volumes:
            - .:/application/pajak
            - ./docker/cache/root:/root
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        networks:
            - app-network
    mysql:
        image: mysql:5.7.22
        ports:
            - "3306:3306"
        networks:
            - app-network
        environment:
            - "MYSQL_DATABASE=pajak"
            - "MYSQL_USER=pajak"
            - "MYSQL_PASSWORD=pajak"
            - "MYSQL_ROOT_PASSWORD=root"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf
            - .:/application/pajak

volumes:
    mysql_data:
        driver: local

networks:
    app-network:
        driver: bridge