version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:8080"
        volumes:
            - .:/application/pajak
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - network
    php:
        build: ./docker/php
        volumes:
            - .:/application/pajak
            - ./docker/cache/root:/root
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        extra_hosts:
            - "pajak.local:172.15.0.1"
        networks:
            - network
    postgres:
        image: postgres:9.6
        ports:
            - "5432:5432"
        networks:
            - network
        environment:
            POSTGRES_USER: pajak
            POSTGRES_PASSWORD: pajak
            POSTGRES_DB: pajak
        volumes:
            - pajak_pgdata:/var/lib/postgresql/data
            - .:/application/pajak
volumes:
    pajak_pgdata: {}

networks:
    network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.15.0.0/16
                  gateway: 172.15.0.1